---
- name: Ensure PostgreSQL Python libraries are installed.
  pip:
    name: "{{ postgresql_python_library }}"
    executable: pip3.7
    state: present

- name: Ensure PostgreSQL packages are installed.
  homebrew:
    name: "{{ postgresql_packages }}"
    state: present

- name: Force-restart PostgreSQL
  command: brew services start postgresql@10
