---
- name: Ensure PostgreSQL Python libraries are installed.
  pip:
    name: "{{ postgresql_python_library }}"
    state: present

- name: Ensure PostgreSQL packages are installed.
  homebrew:
    name: "{{ postgresql_packages }}"
    state: present

- name: ensure PostgreSQL started and enabled on boot
  command: brew services start postgresql@10
